#!/usr/bin/env bash
# Display all listening TCP/UDP sockets with PID/program name
echo "Active Internet connections (only servers)"
netstat -tulnp
echo "Active UNIX domain sockets (only servers)"
netstat -lxnp
