#!/usr/bin/env bash
#A bash script
sudo sed -i '/localhost/d' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" >> /etc/hosts | sudo tee -a /etc/hosts > /dev/null
